### ISSUE TITLE
Contest number

### ISSUE THREAD

**Issue by khazhix** [sukeesh/GoCF#3]
Hello, sukeesh
I found little bug in your code while testing.
I tried to import first contest from CF and then run tests.
Import was great but **gocf 1_A.cpp** didn't work. So I checked code and found that filename should consist of 3 digits. **gocf 001_A.cpp** works great. 
I hope you will improve your code, because in near future there maybe 4 digits contest (ex 1001..).

GoCF really helpful, thank you!

**Comment by sukeesh** [comment]
Yeah,
I didn't test it with the old contests but it can fixed easily :smiley: .
Thanks for reporting and Glad it helped :grinning:
