### ISSUE TITLE
Wrongly creates file in Fedora 25

### ISSUE THREAD

**Issue by aman935** [sukeesh/GoCF#5]
The GoCF folder that it creates after installation is situated in root/GoCF while when i run incf it gives error : 

python: can't open file '/home/aman/GoCF/Parse.py': [Errno 2] No such file or directory 

I had to manually paste the file to GoCF in my home/user/ .

Please look into that.

**Comment by sukeesh** [comment]
Can you please paste the output when you execute the install.sh line-by-line ?
and let me know what happens when you do this `mkdir ~/GoCF`

**Comment by aman935** [comment]
First it was saying "./install.sh Permission denied".
Then i gave "sudo bash ./install.sh". It created that directory GoCF in root/GoCF. 
I think this is specific for the Fedora environment as it may have different privileges for any user. When i give mkdir ~/GoCF . It simply creates a directory in home/user/ .
